name: test all

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python setup.py install
          python example/example_hide_as_img.py
          python example/example_hide_in_img.py
          python example/example_img_exif.py
          python example/example_hide_as_music.py
          python example/example_hide_in_music.py
          python example/example_img_seed.py
          python example/example_hide_as_txt.py
          python example/example_hide_in_txt.py
          python example/example_mirage_tank.py
